a=int(input("enter the first number: "))
b=int(input("enter the second number: "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

x=input("enter first name")
y=input("enter last name")
print(f"Hello,{x} {y}!Welcome to python program.")
